# C?u hình server và ?ng d?ng
server:
  port: 9200

spring:
  application:
    name: ecommerce
    serverName: http://localhost:8080
  
  # C?u hình k?t n?i c? s? d? li?u (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    username: postgres
    password: 123456
  
  # C?u hình JPA và Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # C?u hình g?i email (Gmail SMTP)
  mail:
    from: khainv2k3@gmail.com
    host: smtp.gmail.com
    port: 587
    username: khainv2k3@gmail.com
    password: zdvnrqfjwabahdxr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # C?u hình t?i file lên
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # C?u hình Kafka
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true

# C?u hình endpoint t? ??nh ngh?a
endpoint:
  confirmUser: http://localhost:${server.port}/user/confirm

app:
  